
set(CMAKE_SYSTEM_ARCH w65)

set(SNESDEV_TARGET w65-snesdev-elf)
set(SNESDEV_FORMAT elf32-w65)

find_program(CMAKE_C_COMPILER NAMES $Env{CC} ${SNESDEV_TARGET}-cc ${SNESDEV_TARGET}-gcc ${SNESDEV_TARGET}-clang ${SNESDEV_TARGET}-lccc clang lccc)
find_program(CMAKE_CXX_COMPILER NAME SEnv{CXX} ${SNESDEV_TARGET}-c++ ${SNESDEV_TARGET}-g++ ${SNESDEV_TARGET}-clang ${SNESDEV_TARGET}-lccc clang lccc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})

set(CMAKE_C_COMPILER_TARGET ${SNESDEV_TARGET})
set(CMAKE_CXX_COMPILER_TARGET ${SNESDEV_TARGET})
set(CMAKE_ASM_COMPILER_TARGET ${SNESDEV_TARGET})
