name: C/C++ CI Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  native:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
          target: [w65-snes-elf]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true 
    - name: Install Toolchain
      run: sudo apt install gcc g++
    - name: Setup
      run: |
          mkdir -pv ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        ../SNES-Dev/configure --prefix ${{runner.workspace}}/.ciprefix --target ${{matrix.target}}
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        make -j4
  cross:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
          target: [w65-snes-elf]
          host: [aarch64-linux-gnu, arm-linux-gnueabi, i686-linux-gnu]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true 
    - name: Install Toolchain
      run: sudo apt install gcc g++ gcc-${{matrix.host}} g++-${{matrix.host}}
    - name: Setup
      run: |
          mkdir -pv ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        ../SNES-Dev/configure --prefix ${{runner.workspace}}/.ciprefix --target ${{matrix.target}} --host ${{matrix.host}}
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        make -j4
    